---
title: "Project"
output:
  html_document:
    toc: yes
    toc_float: yes
---

### 1. Overall Goals and Principles

Your final assignment in this course will be to work on a group data science project. The goal of the project is to go through the complete data science process to answer questions you have about some topic of your choosing. You will need to acquire your data, design your visualizations, run analyses, and communicate the results. The project is an opportunity to show off what you’ve learned about data science. Your task is to use data to tell us something interesting. This project is deliberately open-ended to allow you to fully explore your creativity. Here are the main rules that must be followed:

**Use the materials learned in this class.** Both the computational and statistical tools learned.

**Your project must be centered around real data.** You will work with large, complex, and/or messy data. While this is not an explicit requirement of the project, the more challenging your data set is, the more you will have to use the tools learned in this class. For example, one thing that will make your data science project more ambitious is combining two or more data sets that are not directly related.

**Your project must tell us something.** There is a range of data science projects that can satisfy this. We’ve seen a range of examples over the course of the semester. On one extreme would be a strict visualization based project that involves little statistical analysis. On the other extreme are data mining/machine learning projects, which involve no visualization. Your project can be anywhere on this spectrum, but expectations may be different depending on where you are on the scale. An example of a project that doesn’t tell us anything, would be something that downloads a single data source and summarizes it, with some perfunctory visualization. Make sure that your project is thought-provoking and has some underlying meaning!

**Cleverness and creativity will be rewarded.** Going above and beyond what we did in class will be rewarded.



### 2. Project Deadlines/Checkpoints

A timeline of the project is:

* Week 7: Proposal due 2/15 at 1:50 p.m.
* Week 8: Data collection and cleaning finished
* Week 9: EDA finished
* Week 10: Analysis finished
* Tuesday, March 14: Written report due at 11:30 a.m. and oral presentations begin



### 3. Teams

You will work closely with other classmates in a 3-4 person project team. If you can't find a partner I will randomly assign you to a team. In general, I do not anticipate that the grades for each group member will be different; however, I reserve the right to assign different grades to each group member based on peer assessments of your contributions.


### 4. The proposal

Your proposal is to be submitted in print or electronically. Once you decide on a topic that interests you, think about what you would like to end up with as a final result without worrying about how to get there. Try to visualize what your end product will look like. Will it be an interactive map? A predictive model? Don’t think about coding, or a particular data set, or what you know how to do now. If you come up with something ambitious and original, you’ll be more motivated to learn new things as you go in order to accomplish your goal. The topic is completely open to your choice, but keep in mind the rules listed above.

Your proposals should contain the following content:

- Title: The title of your project
- Purpose: Describe the general topic/phenomenon you want to explore, as well some carefully considered questions that you hope to address. You should make an argument motivating your work. Why should someone be interested in what you are doing? What do you hope people will learn from your project?
- Data: As best you can, describe where you will find your data, and what kind of data it is. Will you be working with spatial data in shapefiles? Where will you be accessing you data? Be as specific as you can, listing URLs and file formats if possible.
- Variables: List, and briefly describe, each variable that you plan to incorporate. If you can, be specific about units, scale, etc.
- End Product: Describe what you hope to deliver as a final product.
    + Will it be an interactive application that will be posted on the Internet?
    + Will it be a paper that draws some statistical conclusions?
    + Will it be a model that classifies observations into groups?


### 5. The presentation

An effective oral presentation is an integral part of this project. One of the objectives of this class is to give you experience conveying the results of a technical investigation to a non-technical audience in a way that they can understand. Whether you choose to stay in academia or pursue a career in industry, the ability to communicate clearly is of paramount importance. As a data scientist, the burden of proof is on you to convince your audience that what you are saying is true. If your audience (who may very well be less knowledgeable about statistics than you are) cannot understand your results or their interpretations, then the technical merit of your project is irrelevant.

During the the final exam period, each group will give a 15 minute presentation of your work. Your goal should be to convey to your audience a clear understanding of your research topic, along with a basic understanding of your project, and how well it addresses the research question you posed. You should not tell us everything that you did, or show a bunch of things that you tried that didn’t work well. After hearing your talk, each student in the class should be able to answer:

1. What was your project about?
2. What was your data like, and what techniques did you apply to it?
3. What were your findings?

You should prepare electronic slides for your talk. PowerPoint/Keynote is fine, but you might also want to consider

- RStudio tools: R Markdown slides
- Beamer (LaTeX)
- Google Slides

#### Advice 

- Budget your time. You only have 15 minutes and we will be running a very tight schedule. Plan for 12 minutes to talk, and 3 minutes to answer questions. Rehearse your talk ahead of time several times in order to get a better feel for your timing.
- As a rule of thumb I use the one minute per slide rule.
- Don't write too much on each slide. You don’t want people to have to read your slides, because if the audience is reading your slides, then they aren’t listening to you.
- Put your problem in context. Remember that most of your audience will have little or no knowledge of your subject matter. The easiest way to lose people is to dive right into technical details that require prior domain knowledge. Spend a few minutes at the beginning of your talk introducing your audience to the most basic aspects of your topic and present some motivation for what you are studying.
- Speak loudly and clearly. Remember that you know more about your topic that anyone else in the room, so speak and act with confidence!


### 6. Report

Your report must be a reproducible R Markdown HTML document that when printed is of length no more than 15 pages---i.e. I should be able to recreate your entire analysis with one click of the mouse.

In your write-up, you should tell a data science audience about your project, why they should care about it, and what you have discovered. Your audience will be people like you: current or aspiring data scientists. Keep in mind that this audience is extraordinarily diverse in terms of skills and abilities, so you should assume very little about what they might know. However, your audience is reasonably tech-savvy, so you need not "dumb-down" your analysis. Your write-up should make it clear to me and any other student in the class what methods and techniques you have used to produce your finished product.


#### Content

Do not present *all* of the R code that you wrote throughout the process of working on this project. In fact

- The amount of R code in the **outputted** document should be minimal. The less R code the better.
- Important conclusions should appear in the main text, not in comments in the code.
- The R markdown file should contain the necessary and sufficient (i.e. minimal) set of R code that is necessary to understand your results and findings. If you make a claim, it must be justified by explicit calculation. A knowledgeable reviewer should be able to reproduce your analysis:
    + Compile your .Rmd file without modification
    + Verify every statement that you have made.


#### Motivation

Be sure to motivate your topic at the beginning of your write-up. You should try to hook the reader early on. Assume that your audience is a skeptical data scientist who has stumbled across your report but has very little time to read it. Can you give them a reason to continue reading? A cool visualization or result can help.

#### Format

You don’t need to follow a specific format in the write-up, but you should start with an introductory paragraph and finish with a conclusion. Your write-up should address the following questions:

1. Why should anyone care about this?
2. What is this about? Do not assume that your readers have any domain knowledge! The burden of explanation as to what you are talking about is on you! For example, if your project involves phyllogenetic trees, do not assume that your audience has anything other than a basic, lay understanding of genetics.
3. Where did your data come from? What kind of data was it? Is there a link to the data or some other way for the reader to follow up on your work?
4. What are your findings? What kind of statistical computations (if any) have you done to support those conclusions? Again, while the R code will show you performing the calculation, it is up to you to interpret, in English sentences, the results of these calculations. Do not forget about units, axis labels, etc.
5. What are the limitations of your work? Be clear so that others do not misinterpret your findings. To what population do your results apply? Do they generalize? How could your study be improved? Suggesting plausible extensions don’t weaken your work, they strengthen it by connecting it to future work.

#### Style

The write-up can have interactive components. Take advantage of this by including hyperlinks, figures, videos, etc. to provide context for the reader. You can even include a [bibiliography](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html), and your references should be embedded via links. Use Markdown elements like links, lists, LaTeX, and images as needed.

Visualizations, particularly interactive ones, will be well-received. That said, do not overuse visualizations. You may be better off with one complicated but well-crafted visualization as opposed to many quick-and-dirty plots. Any plots should be well-thought out, properly labelled, informative, and visually appealing!

<!-- ### R Markdown Process Book -->

<!-- An important part of your project is your R Markdown process book. Your process book details the steps you take in developing your solution, including how you collected the data, alternative solutions you tried, describing statistical methods you used, and the insights you got. Equally important to your final results is how you got there! Your process book is the place you describe and document the space of possibilities you explored at each step of your project. We strongly advise you to include many visualizations in your process book. Your process book should include the following topics. Depending on your project type the amount of discussion you devote to each of them will vary: -->

<!-- * Overview and Motivation: Provide an overview of the project goals and the motivation for it. Consider that this will be read by people who did not see your project proposal. -->

<!-- * Related Work: Anything that inspired you, such as a paper, a web site, or something we discussed in class. -->

<!-- * Initial Questions: What questions are you trying to answer? How did these questions evolve over the course of the project? What new questions did you consider in the course of your analysis?  -->

<!-- * Data: Source, scraping method, cleanup, storage, etc. -->

<!-- * Exploratory Data Analysis: What visualizations did you use to look at your data in different ways? What are the different statistical methods you considered? Justify the decisions you made, and show any major changes to your ideas. How did you reach these conclusions? -->

<!-- * Final Analysis: What did you learn about the data? How did you answer the questions? How can you justify your answers? -->

<!-- * Presentation: Present your final results in a compelling and engaging way using text, visualizations, images, and videos. -->


### Code

I expect you to write high-quality and readable R code as part of your final report. You should strive to do things the right way and think about aspects such as reusability, error handling, etc. I also expect you to comment your code.

### Rubrics

* [Presentation rubric](https://docs.google.com/spreadsheets/d/1po3LOj-hWa5ZvI6QkXnFRx7tFNwx0OAjdCVbBvkbR-Y/edit?usp=sharing)

* [Report rubric](https://docs.google.com/spreadsheets/d/1x8aLGfhiVSRyP4ATaa7pGMkfRBZgA9vFbWJSFGi8uzo/edit?usp=sharing)


### Acknowledgements 

The project description was adapted from [Albert Kim](https://rudeboybert.github.io/MATH216/assets/Final_Project/project.html) and [CS109](http://cs109.github.io/2015/pages/projects.html) at Harvard. 